In [3]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [4]:
fake = pd.read_csv("data/Fake.csv")
true = pd.read_csv("data/True.csv")

print(fake.shape)
print(true.shape)

(23481, 4)
(21417, 4)

In [5]:
fake["label"] = 0
true["label"] = 1

In [6]:
news = pd.concat([fake, true], ignore_index=True)

print(news.shape)

(44898, 5)

In [5]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [7]:
news.info()

<class 'pandas.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  str
 1   text     44898 non-null  str
 2   subject  44898 non-null  str
 3   date     44898 non-null  str
 4   label    44898 non-null  int64
dtypes: int64(1), str(4)
memory usage: 1.7 MB

In [8]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [8]:
news.duplicated().sum()

np.int64(209)

In [1]:
import pandas as pd
import numpy as np

In [2]:
fake = pd.read_csv("data/Fake.csv")
true = pd.read_csv("data/True.csv")

In [3]:
fake["label"] = 0
true["label"] = 1

In [4]:
news = pd.concat([fake, true], ignore_index=True)

In [5]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [6]:
news.shape

(44898, 5)

In [7]:
news.columns

Index(['title', 'text', 'subject', 'date', 'label'], dtype='str')

In [8]:
news.info()

<class 'pandas.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  str
 1   text     44898 non-null  str
 2   subject  44898 non-null  str
 3   date     44898 non-null  str
 4   label    44898 non-null  int64
dtypes: int64(1), str(4)
memory usage: 1.7 MB

In [9]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [10]:
news.duplicated().sum()

np.int64(209)

In [11]:
news["label"].value_counts()

label
0    23481
1    21417
Name: count, dtype: int64

In [12]:
news = news.sample(frac=1, random_state=42)
news.reset_index(drop=True, inplace=True)

In [13]:
news = news[["text", "label"]]

In [14]:
news.head()

                                                text  label
0  21st Century Wire says Ben Stein, reputable pr...      0
1  WASHINGTON (Reuters) - U.S. President Donald T...      1
2  (Reuters) - Puerto Rico Governor Ricardo Rosse...      1
3  On Monday, Donald Trump once again embarrassed...      0
4  GLASGOW, Scotland (Reuters) - Most U.S. presid...      1

In [15]:
!pip install nltk

Collecting nltk
  Using cached nltk-3.10.0-py3-none-any.whl.metadata (3.2 kB)
Collecting defusedxml (from nltk)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting click (from nltk)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting regex>=2021.8.3 (from nltk)
  Using cached regex-2026.6.28-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Using cached tqdm-4.68.4-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from click->nltk) (0.4.6)
Using cached nltk-3.10.0-py3-none-any.whl (1.7 MB)
Using cached regex-2026.6.28-cp314-cp314-win_amd64.whl (280 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached tqdm-4.68.4-py3-none-any.whl (676 kB)
Installing collected packages: tqdm, regex, joblib, defusedxml, click, nltk

   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   -------------------- ------------------- 3/6 [defusedxml]
   -------------------- ------------------- 3/6 [defusedxml]
   -------------------------- ------------- 4/6 [click]
   -------------------------- ------------- 4/6 [click]
   -------------------------- ------------- 4/6 [click]
   -------------------------- ------------- 4/6 [click]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   ---------------------------------------- 6/6 [nltk]

Successfully installed click-8.4.2 defusedxml-0.7.1 joblib-1.5.3 nltk-3.10.0 regex-2026.6.28 tqdm-4.68.4

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [17]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\azhar\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [18]:
stop_words = set(stopwords.words("english"))
ps = PorterStemmer()

In [19]:
def clean_text(text):
    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"[^a-zA-Z]", " ", text)

    words = text.split()

    words = [ps.stem(word) for word in words if word not in stop_words]

    return " ".join(words)

In [20]:
news["text"] = news["text"].apply(clean_text)

In [21]:
news.head()

                                                text  label
0  st centuri wire say ben stein reput professor ...      0
1  washington reuter u presid donald trump remov ...      1
2  reuter puerto rico governor ricardo rossello s...      1
3  monday donald trump embarrass countri accident...      0
4  glasgow scotland reuter u presidenti candid go...      1

In [12]:
X = news["text"]
y = news["label"]

In [13]:
print(type(X))
print(X.shape)

<class 'pandas.Series'>
(44898,)

In [15]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from scikit-learn) (2.5.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: joblib>=1.4.0 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from scikit-learn) (1.5.3)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
Using cached scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed narwhals-2.23.0 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(X)

print(X.shape)

(44898, 5000)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [18]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (35918, 5000)
X_test: (8980, 5000)
y_train: (35918,)
y_test: (8980,)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
model = LogisticRegression(max_iter=1000)

In [21]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [22]:
y_pred = model.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9869710467706013

In [24]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4733
           1       0.99      0.99      0.99      4247

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

In [25]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[4670   63]
 [  54 4193]]

In [26]:
import joblib

joblib.dump(model, "fake_news_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Model Saved Successfully!")

Model Saved Successfully!

In [27]:
def predict_news(news_text):
    text = vectorizer.transform([news_text])
    prediction = model.predict(text)

    if prediction[0] == 0:
        return "Fake News"
    else:
        return "Real News"

In [31]:
news = input("Enter News: ")

print(predict_news(news))

Real News

In [32]:
!pip install streamlit

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting streamlit
  Using cached streamlit-1.59.1-py3-none-any.whl.metadata (9.6 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Using cached altair-6.2.2-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<8,>=5.5 (from streamlit)
  Using cached cachetools-7.1.4-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from streamlit) (8.4.2)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Using cached gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from streamlit) (2.5.1)
Requirement already satisfied: packaging>=20 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from streamlit) (3.0.3)
Collecting pillow<13,>=7.1.0 (from streamlit)
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting protobuf<8,>=3.20 (from streamlit)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-25.0.0-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Collecting requests<3,>=2.27 (from streamlit)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from streamlit) (4.16.0)
Collecting starlette>=0.40.0 (from streamlit)
  Using cached starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Collecting uvicorn>=0.30.0 (from streamlit)
  Using cached uvicorn-0.51.0-py3-none-any.whl.metadata (6.6 kB)
Collecting httptools>=0.6.3 (from streamlit)
  Using cached httptools-0.8.0-cp314-cp314-win_amd64.whl.metadata (3.7 kB)
Collecting anyio>=4.0.0 (from streamlit)
  Using cached anyio-4.14.1-py3-none-any.whl.metadata (4.6 kB)
Collecting python-multipart>=0.0.10 (from streamlit)
  Using cached python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Collecting websockets>=12.0.0 (from streamlit)
  Downloading websockets-16.1-cp314-cp314-win_amd64.whl.metadata (7.0 kB)
Collecting itsdangerous>=2.1.2 (from streamlit)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.23.0)
Requirement already satisfied: colorama in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.27->streamlit)
  Using cached charset_normalizer-3.4.9-cp314-cp314-win_amd64.whl.metadata (42 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.27->streamlit)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests<3,>=2.27->streamlit)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.27->streamlit)
  Using cached certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Collecting MarkupSafe>=2.0 (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached markupsafe-3.0.3-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached rpds_py-2026.6.3-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\azhar\onedrive\documents\fake_news\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Collecting h11>=0.8 (from uvicorn>=0.30.0->streamlit)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Using cached streamlit-1.59.1-py3-none-any.whl (10.3 MB)
Using cached altair-6.2.2-py3-none-any.whl (797 kB)
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Using cached cachetools-7.1.4-py3-none-any.whl (16 kB)
Using cached gitpython-3.1.50-py3-none-any.whl (212 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Using cached pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.9-cp314-cp314-win_amd64.whl (162 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached smmap-5.0.3-py3-none-any.whl (24 kB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Using cached anyio-4.14.1-py3-none-any.whl (124 kB)
Using cached certifi-2026.6.17-py3-none-any.whl (133 kB)
Using cached httptools-0.8.0-cp314-cp314-win_amd64.whl (92 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached markupsafe-3.0.3-cp314-cp314-win_amd64.whl (15 kB)
Downloading pyarrow-25.0.0-cp314-cp314-win_amd64.whl (28.6 MB)
   ---------------------------------------- 0.0/28.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/28.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/28.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/28.6 MB ? eta -:--:--
    --------------------------------------- 0.5/28.6 MB 970.0 kB/s eta 0:00:29
   - -------------------------------------- 0.8/28.6 MB 1.0 MB/s eta 0:00:27
   - -------------------------------------- 1.0/28.6 MB 1.1 MB/s eta 0:00:26
   -- ------------------------------------- 1.6/28.6 MB 1.2 MB/s eta 0:00:22
   -- ------------------------------------- 1.8/28.6 MB 1.3 MB/s eta 0:00:22
   --- ------------------------------------ 2.6/28.6 MB 1.6 MB/s eta 0:00:17
   ---- ----------------------------------- 2.9/28.6 MB 1.6 MB/s eta 0:00:16
   ---- ----------------------------------- 3.4/28.6 MB 1.7 MB/s eta 0:00:15
   ----- ---------------------------------- 4.2/28.6 MB 1.9 MB/s eta 0:00:14
   ------ --------------------------------- 4.7/28.6 MB 1.9 MB/s eta 0:00:13
   ------- -------------------------------- 5.2/28.6 MB 2.0 MB/s eta 0:00:12
   -------- ------------------------------- 6.0/28.6 MB 2.1 MB/s eta 0:00:11
   --------- ------------------------------ 6.6/28.6 MB 2.1 MB/s eta 0:00:11
   ---------- ----------------------------- 7.3/28.6 MB 2.2 MB/s eta 0:00:10
   ---------- ----------------------------- 7.9/28.6 MB 2.3 MB/s eta 0:00:10
   ------------ --------------------------- 8.9/28.6 MB 2.4 MB/s eta 0:00:09
   ------------- -------------------------- 9.4/28.6 MB 2.4 MB/s eta 0:00:08
   -------------- ------------------------- 10.5/28.6 MB 2.5 MB/s eta 0:00:08
   --------------- ------------------------ 11.3/28.6 MB 2.6 MB/s eta 0:00:07
   ---------------- ----------------------- 11.5/28.6 MB 2.6 MB/s eta 0:00:07
   ----------------- ---------------------- 12.3/28.6 MB 2.6 MB/s eta 0:00:07
   ------------------ --------------------- 13.1/28.6 MB 2.6 MB/s eta 0:00:06
   ------------------- -------------------- 14.2/28.6 MB 2.7 MB/s eta 0:00:06
   -------------------- ------------------- 14.9/28.6 MB 2.8 MB/s eta 0:00:05
   --------------------- ------------------ 15.7/28.6 MB 2.8 MB/s eta 0:00:05
   ----------------------- ---------------- 16.5/28.6 MB 2.8 MB/s eta 0:00:05
   ----------------------- ---------------- 17.0/28.6 MB 2.8 MB/s eta 0:00:05
   ------------------------ --------------- 17.8/28.6 MB 2.9 MB/s eta 0:00:04
   -------------------------- ------------- 18.9/28.6 MB 2.9 MB/s eta 0:00:04
   --------------------------- ------------ 19.7/28.6 MB 2.9 MB/s eta 0:00:04
   ---------------------------- ----------- 20.2/28.6 MB 2.9 MB/s eta 0:00:03
   ----------------------------- ---------- 21.0/28.6 MB 3.0 MB/s eta 0:00:03
   ------------------------------ --------- 21.8/28.6 MB 3.0 MB/s eta 0:00:03
   ------------------------------- -------- 22.5/28.6 MB 3.0 MB/s eta 0:00:03
   -------------------------------- ------- 23.3/28.6 MB 3.0 MB/s eta 0:00:02
   --------------------------------- ------ 24.1/28.6 MB 3.0 MB/s eta 0:00:02
   ---------------------------------- ----- 24.9/28.6 MB 3.1 MB/s eta 0:00:02
   ----------------------------------- ---- 25.4/28.6 MB 3.0 MB/s eta 0:00:02
   ----------------------------------- ---- 25.7/28.6 MB 3.0 MB/s eta 0:00:01
   ------------------------------------ --- 26.2/28.6 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 26.7/28.6 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 27.0/28.6 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 27.5/28.6 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 27.8/28.6 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  28.6/28.6 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 28.6/28.6 MB 2.9 MB/s  0:00:10
Using cached python_multipart-0.0.32-py3-none-any.whl (30 kB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached rpds_py-2026.6.3-cp314-cp314-win_amd64.whl (220 kB)
Using cached starlette-1.3.1-py3-none-any.whl (73 kB)
Using cached uvicorn-0.51.0-py3-none-any.whl (73 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Downloading websockets-16.1-cp314-cp314-win_amd64.whl (180 kB)
Installing collected packages: websockets, watchdog, urllib3, toml, tenacity, smmap, rpds-py, python-multipart, pyarrow, protobuf, pillow, MarkupSafe, itsdangerous, idna, httptools, h11, charset_normalizer, certifi, cachetools, blinker, attrs, uvicorn, requests, referencing, jinja2, gitdb, anyio, starlette, pydeck, jsonschema-specifications, gitpython, jsonschema, altair, streamlit

   ----------------------------------------  0/34 [websockets]
   ----------------------------------------  0/34 [websockets]
   ----------------------------------------  0/34 [websockets]
   ----------------------------------------  0/34 [websockets]
   ----------------------------------------  0/34 [websockets]
   - --------------------------------------  1/34 [watchdog]
   - --------------------------------------  1/34 [watchdog]
   - --------------------------------------  1/34 [watchdog]
   - --------------------------------------  1/34 [watchdog]
   - --------------------------------------  1/34 [watchdog]
   - --------------------------------------  1/34 [watchdog]
   - --------------------------------------  1/34 [watchdog]
   - --------------------------------------  1/34 [watchdog]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   -- -------------------------------------  2/34 [urllib3]
   --- ------------------------------------  3/34 [toml]
   --- ------------------------------------  3/34 [toml]
   --- ------------------------------------  3/34 [toml]
   ---- -----------------------------------  4/34 [tenacity]
   ---- -----------------------------------  4/34 [tenacity]
   ---- -----------------------------------  4/34 [tenacity]
   ---- -----------------------------------  4/34 [tenacity]
   ----- ----------------------------------  5/34 [smmap]
   ----- ----------------------------------  5/34 [smmap]
   ----- ----------------------------------  5/34 [smmap]
   ------- --------------------------------  6/34 [rpds-py]
   -------- -------------------------------  7/34 [python-multipart]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   --------- ------------------------------  8/34 [pyarrow]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ---------- -----------------------------  9/34 [protobuf]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]
   ----------- ---------------------------- 10/34 [pillow]